:language: Swedish
:!english:
:swedish:
:!danish:
:norwegian:
= Multi-language document example
:author: Mitt Namn
:email: <mitt.email@adress.here>
:author_2: Hans Namn
:email_2: <hans.email@adress.here>

////
Author(s) and their email-adresses are only expected to be found in the "main" document.
Because of this, if we want to have separate authors for sub-documents, these will have to be written out using the explicit style.
The first author corresponds to {author} and {email}, the second author corresponds to {author_2} and {email_2}.
////

////
First example uses a shared variable that can only be set to one language
////

{author} är den primära författaren, {author_2} hjälper till!

ifeval::["{language}" == "English"]
[NOTE]
====
Only show me if the language is set to English!
====
endif::[]

ifeval::["{language}" == "Swedish"]
[NOTE]
====
Detta visas bara om language[] är satt till Svenska!
((("språk", "bäst", "patriot")))
====
endif::[]


ifeval::["{language}" == "Danish"]
[NOTE]
====
"oförståeligt uttal"
====
endif::[]

ifeval::["{language}" == "Norwegian"]
[NOTE]
====
"som en lite för överförfriskad svensk"
====
endif::[]

////
The second example checks if a variable has been defined or not,
allowing for multiple blocks to be shown by defining them.
////

ifdef::english[]
[NOTE]
====
Only shown if the variable english[] has been set!
====
endif::[]

ifdef::swedish[]
[NOTE]
====
Visas bara om variabeln swedish[] är definerad.
====
endif::[]


ifdef::danish[]
[NOTE]
====
"oförståeligt uttal", men bara om danish[] är definerad.
====
endif::[]

ifdef::norwegian[]
[NOTE]
====
"som en lite för överförfriskad svensk", men bara om norwegian[] är definerad
====
endif::[]