:language: Swedish
:english:
:swedish:
:!danish:
:!norwegian:
= Multi-language document example
:author: Mitt Namn
:email: <mitt.email@adress.here>
:author_2: Hans Namn
:email_2: <hans.email@adress.here>

////
Author(s) and their email-adresses are only expected to be found in the "main" document.
Because of this, if we want to have separate authors for sub-documents, these will have to be written out using the explicit style.
The first author corresponds to {author} and {email}, the second author corresponds to {author_2} and {email_2}.
////

////
First example uses a shared variable that can only be set to one language
////

{author} är den primära författaren, {author_2} hjälper till!

ifeval::["{language}" == "English"]
[NOTE]
====
\{language\} is set to "English"
((("language-family", "germanic", "west germanic")))
====
endif::[]

ifeval::["{language}" == "Swedish"]
[NOTE]
====
\{language\} är satt till "Swedish"
((("language-family", "germanic", "north germanic")))
====
endif::[]


ifeval::["{language}" == "Danish"]
[NOTE]
====
\{language\} er indstillet til "Danish"
((("language-family", "germanic", "north germanic")))
====
endif::[]

ifeval::["{language}" == "Norwegian"]
[NOTE]
====
\{language\} er satt til "Norwegian"
((("language-family", "germanic", "north germanic")))
====
endif::[]

////
The second example checks if a variable has been defined or not,
allowing for multiple blocks to be shown by defining them.
////

ifdef::english[]
[NOTE]
====
Only shown if the variable english[] is defined.
((("language-family", "germanic", "west germanic")))
====
endif::[]

ifdef::swedish[]
[NOTE]
====
Visas bara om variabeln swedish[] är definerad.
((("language-family", "germanic", "north germanic")))
====
endif::[]

ifdef::danish[]
[NOTE]
====
Vises kun om variablen danish[] er defineret.
((("language-family", "germanic", "north germanic")))
====
endif::[]

ifdef::norwegian[]
[NOTE]
====
Vises bare hvis variabelen norwegian[] er definert.
((("language-family", "germanic", "north germanic")))
====
endif::[]